πGET http://localhost:3003/api/blogs 

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY5YTU2ZjQwNzhlNTIwYTM0MWVlNGRhNyIsImlhdCI6MTc3MjQ1MzY1MX0.VIgyBS1R3AxREupSyNugsgSvFxIJFzsE11lbUJexuog

{
  "author":"me",
  "url": "hey",
  "title":"filled",
  "likes":5
}

###
DELETE http://localhost:3003/api/blogs/69a0551a9d8b529d4907bffd
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY5YTU2ZjQwNzhlNTIwYTM0MWVlNGRhNyIsImlhdCI6MTc3MjQ1MzY1MX0.VIgyBS1R3AxREupSyNugsgSvFxIJFzsE11lbUJexuog
###
PUT  http://localhost:3003/api/blogs/6 HTTP/1.1
content-type: application/json

{
  "author":"45688614",
  "url": "646841",
  "likes":55,
  "id":54
}

###
POST  http://localhost:3003/api/users HTTP/1.1
content-type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc2FzYXNrbG9qdWhqb3BvYXMiLCJpZCI6IjY5YTAyMjkwZDZhMWYzZjMxYTk3YzhiNyIsImlhdCI6MTc3MjEwNTM0OH0.9FEkwGjhmzTYERyyaofvcxCaffDnpfdB7nga36boVww'

{
  "username":"45688614",
  "url": "646841",
  "likes":55,
  "id":54
}


###
DELETE http://localhost:3003/api/blogs/drop HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY5YTU2ZjQwNzhlNTIwYTM0MWVlNGRhNyIsImlhdCI6MTc3MjQ1MzY1MX0.VIgyBS1R3AxREupSyNugsgSvFxIJFzsE11lbUJexuog

###
GET http://localhost:3003/api/blogs/many HTTP/1.1

###
PUT http://localhost:3003/api/blogs/69a6d267d424a482b4f1ac46/comments HTTP/1.1
content-type: application/json

{
  "comment":"thats a first comment bro"
}