GET http://localhost:3001/

###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info

### 
//Get person by ID 
GET http://localhost:3001/api/persons/69945021aac7056c45414801

###
//GET person unexisting valid id
GET http://localhost:3001/api/persons/6994501499e2a40e2743d990


###
//GET person malformed id
GET http://localhost:3001/api/persons/54

###
DELETE http://localhost:3001/api/persons/6994501499e2a40e2743d990

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json
{
    "name":"Mike",
    "number":"420-2232323"
}

###
// Validation error
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name":"No",
    "number":"4242424242"
}



###
PUT  http://localhost:3001/api/persons/69947036532a6e0c23ced00c HTTP/1.1
content-type: application/json

{
    "name":"Mike",
    "number":"hgvgv"
}


###
//PUT ERROR
PUT  http://localhost:3001/api/persons/69947036532a6e0c23ced00c HTTP/1.1
content-type: application/json

{
    "name":"Mq",
    "number":"56-6565656wasdsdf"
}


###
GET http://localhost:3001/api/unknowroute