POST http://localhost:3003/calculate HTTP/1.1
content-type: application/json

{
  "value1":5,
  "value2":10,
  "op":"add"
}


###
GET  http://localhost:3000/bmi HTTP/1.1

###
GET  http://localhost:3000/bmi?height=180&weight=72 HTTP/1.1

###
GET  http://localhost:3003/ping HTTP/1.1
