GET http://localhost:3001/api/notes/

###
//inexisting id
GET  http://localhost:3001/api/notes/5c41c90e84d891c15dfa3431

###
//Malformatted id
GET  http://localhost:3001/api/notes/SomeBadFormat


###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "Ensure that everything works",
    "important" :true
}


###
//Bad format 
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important" :true
}
###
PUT http://localhost:3001/api/notes/6994836d77fdd0642ad725fa HTTP/1.1
content-type: application/json

{
    "content": "Ensure that everything works, more",
    "important" :false
}
